files:
  - source: /healthcare/locale/main.pot
    translation: /healthcare/locale/%two_letters_code%.po
pull_request_title: "fix: sync translations from crowdin"
pull_request_labels:
  - translation
  - skip-release-notes
commit_message: "fix: %language% translations"
append_commit_message: false
